apiVersion: v1
kind: Service
metadata:
  name: pd-postgres
  namespace: pd-scanner
  labels:
    app: pd-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: pd-postgres
  clusterIP: None