[mypy]
python_version = 3.11
strict = True
ignore_missing_imports = True
disable_error_code = call-arg

[mypy-src.config.settings]
disable_error_code = call-arg

[mypy-src.core.logger]
disable_error_code = arg-type,no-any-return

[mypy-src.infrastructure.*]
disable_error_code = no-any-return

[mypy-psycopg.*]
ignore_missing_imports = True

[mypy-sqlalchemy.*]
ignore_missing_imports = True

[mypy-pyspark.*]
ignore_missing_imports = True

[mypy-py4j.*]
ignore_missing_imports = True

[mypy-PyPDF2.*]
ignore_missing_imports = True