apiVersion: v1
data:
  KAFKA_BROKER: pd-kafka-0.pd-kafka.pd-scanner.svc.cluster.local
  KAFKA_PORT: '9092'
  KAFKA_TOPIC_EXTRACTED_TEXT: extracted_text
  KAFKA_TOPIC_RAW_FILES: raw_files
  KAFKA_TOPIC_RESULTS: pd_results
kind: ConfigMap
metadata:
  labels:
    app: pd-kafka
  name: pd-kafka-config
  namespace: pd-scanner
