apiVersion: v1
kind: Service
metadata:
  name: pd-kafka
  namespace: pd-scanner
  labels:
    app: pd-kafka
spec:
  ports:
    - port: 9092
      targetPort: 9092
      name: kafka
    - port: 9093
      targetPort: 9093
      name: controller
  selector:
    app: pd-kafka
  clusterIP: None