apiVersion: v1
data:
  SPARK_DRIVER_MEMORY: 1g
  SPARK_EXECUTOR_CORES: '2'
  SPARK_EXECUTOR_MEMORY: 1g
  SPARK_MASTER_HOST: pd-spark-master
  SPARK_MASTER_PORT: '7077'
  SPARK_UI_PORT: '8080'
kind: ConfigMap
metadata:
  labels:
    app: pd-spark
  name: pd-spark-config
  namespace: pd-scanner
